name: Install Dependencies

on:
    # 支持手动触发工作流
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Check Python version
      run: |
        python --version
        which python
    - name: Install dependencies
      run: |
        pip install -r scripts/requirements.txt
